/**
 * Client-side Pagefind adapter.
 *
 * Pagefind is generated by a post-build step (see
 * `src/integrations/pagefind-resources.ts`), so `/pagefind/pagefind.js` only
 * exists in a real build. The import is therefore lazy and guarded: in `astro
 * dev` it simply fails and search degrades to the static in-memory index.
 */
import { pageHref } from "./pageHref";
import type { SearchCategory, SearchItem } from "./searchIndex";

type PagefindResultData = {
  url: string;
  excerpt?: string;
  meta?: Record<string, string | undefined>;
};

/** Strip HTML tags, repeating until no more tags remain so a malformed or
 * nested markup fragment (e.g. `<<script>script>`) can't survive a single pass. */
function stripTags(html: string): string {
  let text = html;
  let previous: string;
  do {
    previous = text;
    text = text.replace(/<[^>]*>/g, " ");
  } while (text !== previous);
  return text;
}


type PagefindModule = {
  options?: (opts: Record<string, unknown>) => Promise<void>;
  init?: () => Promise<void>;
  debouncedSearch?: (
    term: string,
    options?: unknown,
    debounceMs?: number,
  ) => Promise<{ results: { data: () => Promise<PagefindResultData> }[] } | null>;
  search: (
    term: string,
    options?: unknown,
  ) => Promise<{ results: { data: () => Promise<PagefindResultData> }[] }>;
};

/** Site base path, matching the value bootstrapped by `BaseLayout.astro`. */
function basePath(): string {
  const fromDocument =
    typeof document !== "undefined"
      ? document.documentElement.dataset.basePath
      : undefined;
  const base = fromDocument || pageHref();
  return base.endsWith("/") ? base : `${base}/`;
}

let modulePromise: Promise<PagefindModule | null> | null = null;

/** Load (once) the Pagefind bundle, or resolve to `null` when unavailable. */
export function loadPagefind(): Promise<PagefindModule | null> {
  if (modulePromise) return modulePromise;
  modulePromise = (async () => {
    if (typeof window === "undefined") return null;
    try {
      const url = `${basePath()}pagefind/pagefind.js`;
      const mod: PagefindModule = await import(/* @vite-ignore */ url);
      await mod.options?.({ baseUrl: basePath() });
      await mod.init?.();
      return mod;
    } catch {
      // No index (dev server, or a build that skipped Pagefind) — the caller
      // falls back to the static index.
      return null;
    }
  })();
  return modulePromise;
}

const CATEGORY_BY_SEGMENT: Record<string, SearchCategory> = {
  agent: "Agents",
  agents: "Agents",
  instruction: "Instructions",
  instructions: "Instructions",
  skill: "Skills",
  skills: "Skills",
  plugin: "Plugins",
  plugins: "Plugins",
  extension: "Extensions",
  extensions: "Extensions",
  "learning-hub": "Articles",
};

/** Derive a result category from the result URL, relative to the base path. */
function categoryOf(pathname: string): SearchCategory {
  const base = basePath();
  const relative = pathname.startsWith(base)
    ? pathname.slice(base.length)
    : pathname.replace(/^\//, "");
  const segments = relative.split("/").filter(Boolean);
  if (segments.length === 0) return "Pages";
  // A bare section landing page (e.g. /skills/) is a destination, not a record.
  if (segments.length === 1 && !CATEGORY_BY_SEGMENT[segments[0]]) return "Pages";
  if (segments.length === 1) return "Pages";
  return CATEGORY_BY_SEGMENT[segments[0]] ?? "Pages";
}

/** Pagefind custom records carry a `Title — Agent` style suffix; strip it. */
function cleanTitle(title: string): string {
  return title.replace(/\s+—\s+(Agent|Instruction|Skill|Hook|Workflow|Plugin|Tool|Extension)$/u, "");
}

/** Normalised key used to dedupe against the static index. */
export function hrefKey(href: string): string {
  try {
    const url = new URL(href, window.location.origin);
    return url.pathname.replace(/\/+$/, "").toLowerCase() || "/";
  } catch {
    return href.replace(/\/+$/, "").toLowerCase() || "/";
  }
}

/** Run a Pagefind query and adapt the hits to `SearchItem`s. */
export async function searchPagefind(
  term: string,
  limit: number,
): Promise<SearchItem[]> {
  const pagefind = await loadPagefind();
  if (!pagefind) return [];
  try {
    const response = pagefind.debouncedSearch
      ? await pagefind.debouncedSearch(term, undefined, 180)
      : await pagefind.search(term);
    // `debouncedSearch` resolves to null when superseded by a newer query.
    if (!response) return [];
    const data = await Promise.all(
      response.results.slice(0, limit).map((result) => result.data()),
    );
    const items: SearchItem[] = [];
    for (const entry of data) {
      if (!entry?.url) continue;
      const title = cleanTitle(entry.meta?.title?.trim() || entry.url);
      if (!title) continue;
      items.push({
        title,
        description: entry.excerpt ? stripTags(entry.excerpt) : "",
        category: categoryOf(entry.url.split(/[?#]/)[0]),
        href: entry.url,
      });
    }
    return items;
  } catch {
    return [];
  }
}
